name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      GRADLE_OPTS: -Dorg.gradle.caching=true

    steps:
      - uses: actions/checkout@v4.1.4
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: 11
      - uses: gradle/actions/setup-gradle@v3.3.2
        with:
          validate-wrappers: true
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Build with Gradle
        run: ./gradlew assemble
      - name: Test JVM
        run: ./gradlew jvmTest
